services:
  web:
    build: .
    container_name: medilockerai-web
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_DB_HOST: "db"
      DJANGO_DB_NAME: "medilockerai_db"
      DJANGO_DB_USER: "medilockerai_user"
      DJANGO_DB_PASSWORD: "medilockeraipass"

  db:
    image: postgres:latest
    container_name: medilockerai-postgres
    environment:
      POSTGRES_USER: "medilockerai_user"
      POSTGRES_PASSWORD: "medilockeraipass"
      POSTGRES_DB: "medilockerai_db"
    volumes:
      - medilockerai_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  medilockerai_postgres_data:
